### ISSUE TITLE
Color of RayMesh is always blue in the viewport render, whatever color we pick

### ISSUE THREAD

**Issue by bencresty** [BlenderBoi/Radiant#1]
First of all, great plugin. Thanks for this and have a great 2023.
Trying out the RayMesh now, which is a great idea to be able to reduce render times on simple light beams.

But the raymesh doesn't work in the viewport as expected; When adding a RayMesh with Shift + A --> Mesh --> RayMesh, we got a popup to pick a color for the rays, but whatever color we chose, the ray is always blue in the viewport (also in rendered mode). Except for the Text type, there it works as expected with the picked color. Of course I tried in the right viewport render modes and even tried it, next to Eevee, with Cycles. 

Eevee:
![image](https://user-images.githubusercontent.com/69322733/210169793-74b5aab4-823b-452a-b926-e7c22f75a6b2.png)

When doing a render tho it does use the picked color on all meshes, so on render output it works on all meshes:
![image](https://user-images.githubusercontent.com/69322733/210169844-2997628e-5565-4249-8830-b79c995a4828.png)

Guess there's something missing for the render output in the viewport that is not missing on the text mesh?

Used the latest Blender (3.4.1) on Windows and the master of the plugin as-is from today (1-1-2023) here.

**Comment by BlenderBoi** [comment]
I Will Look into it, I think I missed it somewhere, but it will take some time because I am a little busy

**Comment by bencresty** [comment]
No worries. Not in a hurry. Thanks for the great work you do!

**Comment by BlenderBoi** [comment]
Hi, I Checked it out, For Some Reason, The Color is Set Properly, but for some reason blender doesn't update the color in the viewport

all you need to do is just reopen the file or update the value in the object's modifier's geometry node

I think this is a blender bug, i will have to double check

**Comment by BlenderBoi** [comment]
Added a Patch that force update the object after Create, The Problem Should be Solved Now

Get it At:
https://github.com/BlenderBoi/Radiant/releases/tag/v1.3.1

**Comment by bencresty** [comment]
Yes, working fine now! Thanks for the fix!
